[package]
name = "ju_tcs_rust_23_19"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "nie jedzcie ostrego"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ju_tcs_rust_23_19"
path = "src/head_tail.rs"

[dependencies]
