[package]
name = "head_tail"
version = "0.1.0"
edition = "2021"
licence = "MIT"
description = "nie jedzcie ostrego"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "head_tail"
path = "src/head_tail.rs"

[dependencies]
